name: Scheduled Sync

on:
  schedule:
    # Her 5 saatte bir çalışması için cron ifadesi
    - cron: '0 */5 * * *'
  workflow_dispatch: # İstediğinde manuel olarak da başlatabilmen için

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Upstream
        run: |
          # 1. Orijinal repoyu (upstream) ekle
          git remote add upstream https://github.com/qwe213312/k25FCdfEOoEJ42S6.git
          
          # 2. Upstream verilerini çek
          git fetch upstream
          
          # 3. Kendi ana dalına geç (main veya master olduğunu kontrol et)
          git checkout main || git checkout master
          
          # 4. Upstream'deki değişiklikleri birleştir (Merge)
          # --allow-unrelated-histories: Farklı geçmişleri olan repolar için güvenlik önlemi
          git merge upstream/main --allow-unrelated-histories || git merge upstream/master --allow-unrelated-histories
          
          # 5. Kendi forku'na geri yükle (Push)
          git push origin HEAD
